name = "pineapplegallery"
compatibility_date = "2024-11-27"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]


[[r2_buckets]]
binding = "R2"
bucket_name = "pineapplegallery-bucket"

[[d1_databases]]
binding = "DB"
database_name = "pineapplegallery-database"
database_id = "30cffc37-e133-49db-8534-6524c89de2bb"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "42ee21cd50bf44adb285c6c3d02727cd"

#----------------------------------------------------------- CONFIG

[vars]

# Page title
PAGE_TITLE = "Pineapple Gallery"

# Page description
DESCRIPTION = "Pineapple Gallery is a project designed to serve up image galleries using Cloudflare!"

# Copyright attribution name
COPYRIGHT="Pineapple Gallery"

# Image transformations
IMGT = "true"

# Use Cache KV functionality
USE_CACHE = "true"

# Admin Panel Credentials unsoment to set here | commented to set using cf dashboard
# USERNAME = "admin"
# PASSWORD = "superSecretPassword"

# Path to the gallery application (should contain no slashes, unless this serves on root, which then it should be a single slash)
GALLERY_PATH="gallery"
